apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: voting-app
    component: db
spec:
  containers:
    - name: database
      image: postgres:9.6
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: voting-app
    component: db
  ports:
    - port: 5432
