apiVersion: v1
kind: Pod
metadata:
  name: results-app
  labels:
    app: voting-app
    component: results-app
spec:
  containers:
    - name: results-app
      image: dockersamples/examplevotingapp_result

---

apiVersion: v1
kind: Service
metadata:
  name: results-app
spec:
  selector:
    app: voting-app
    component: results-app
  ports:
    - port: 80
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadaa:
  name: results-app
  
spec:
  rules:
  - host: results.local.mikesir87.training
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: results-app
            port: 
              number: 5000
